### ISSUE TITLE
Changing name

### ISSUE THREAD

**Issue by saccarosium** [gbprod/nord.nvim#1]
Is probably a good idea to change the name to something else, since there are a lot of repos called `nord.nvim`. Something like: `nord-nvim`, `nord_nvim`.

**Comment by gbprod** [comment]
I like this name. As all repos maned `nord.nvim` are colorscheme, I don't think that's a problem. No one will install the same theme twice.

Thanks for your feedback ;)

**Comment by saccarosium** [comment]
Was more a discoverability concern. If I search nord.nvim I need to scrool really far.
