### ISSUE TITLE
alpha-nvim support

### ISSUE THREAD

**Issue by mochaaP** [gbprod/nord.nvim#13]
`alpha-nvim`: <https://github.com/goolord/alpha-nvim>

Needed highlights:
- `AlphaButtons`
- `AlphaShortcut`
- `AlphaHeader`

**Comment by Isrothy** [comment]
`alpha-nvim` works well for me.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61075605/214754571-04413b13-49c1-4ea4-8bd0-f0b77fe83732.png">
May I ask what do you want it to look like?

**Comment by gbprod** [comment]
Same for me, It works without setting highlights.
What's your issue ?

**Comment by gbprod** [comment]
And Alpha do not provide any default highlight groups, you have to set them manually in your config (see https://github.com/goolord/alpha-nvim/blob/main/doc/alpha.txt#L165)
So I don't think it's necessary to add custom highlight groups for that :)

Thanks for your feedback
