### ISSUE TITLE
error when applying config

### ISSUE THREAD

**Issue by adetabrani** [gbprod/nord.nvim#19]
![Screenshot from 2023-01-28 09-32-21](https://user-images.githubusercontent.com/47938004/215237775-3aa8b782-e938-4106-bebd-eef972aa5249.png)
how to apply config? when I apply the config I keep getting errors (i have called the config on the first line), sorry if this question seems stupid but I really don't know how to fix it

**Comment by Isrothy** [comment]
Are you using package manager like [Packer](https://github.com/wbthomason/packer.nvim) or [Lazy](https://github.com/folke/lazy.nvim)?

**Comment by adetabrani** [comment]
solved, I think I caught a typo when I did the config earlier
