### ISSUE TITLE
Harsh pink color on syntax error

### ISSUE THREAD

**Issue by trevarj** [gbprod/nord.nvim#24]
In certain files, such as `toml` or `lua` files, if you make a syntax error there is an intense pink as the background color:

![image](https://user-images.githubusercontent.com/5448324/222118612-ffaec60e-6832-4a73-9789-60891f05c724.png)

If I switch themes this doesn't seem to happen. Maybe we can change it to a Nord palette color?

**Comment by gbprod** [comment]
Hey!

Your pikk seems strange, it should be a red (https://github.com/gbprod/nord.nvim/blob/main/lua/nord/colors.lua#L23), do you have colorblind mode enable?

Anyway, you can choose between 3 ways of show your errors by setting error mode in config : 
```lua
require("nord").setup({
  errors = { mode = "bg" }, 
})
```

By default, mode is `bg` and looks like your screenshot. You can also choose `fg` to have red colored  text or `none` to only have undercurled text.

With `fg`
![2023-03-01-120414_358x86_scrot](https://user-images.githubusercontent.com/3751019/222121909-dd910867-f18b-4d8f-93be-27d1fa4d356a.png)

With `none`
![2023-03-01-120031_884x61_scrot](https://user-images.githubusercontent.com/3751019/222121913-864b5880-e892-49f4-aa20-4e49d37a2e91.png)

**Comment by trevarj** [comment]
Thanks for the quick reply!
Yes, colorblind is enabled. Seems that "fg" doesn't make my text red, but I have the underline. Anyway, that's better than the bright pink 😁 

Here is my config:

```
{
    "gbprod/nord.nvim",
    opts = {
      errors = { mode = "fg" },
      styles = {
        -- Style to be applied to different syntax groups
        -- Value is any valid attr-list value for `:help nvim_set_hl`
        comments = { italic = false },
        keywords = { bold = true },
        functions = {},
        variables = {},

        -- To customize lualine/bufferline
        bufferline = {
          current = {},
          modified = { italic = true },
        },
      },

      -- colorblind mode
      -- see https://github.com/EdenEast/nightfox.nvim#colorblind
      -- simulation mode has not been implemented yet.
      colorblind = {
        enable = true,
        preserve_background = true,
        severity = {
          protan = 0.4,
          deutan = 1.0,
          tritan = 0.0,
        },
      },
    },
  },
```

**Comment by gbprod** [comment]
hmm that's strange... I'll take a look
