### ISSUE TITLE
No colors in Magit

### ISSUE THREAD

**Issue by kraanzu** [gbprod/nord.nvim#25]
There are no colors in Magit unlike 'articlestudio/nord'

## gbprod/nord.vim
![image](https://user-images.githubusercontent.com/97718086/222878302-7e562b09-19e3-42e6-9340-ac7ccd340ba1.png)

## articlestudio/nord.vim
![image](https://user-images.githubusercontent.com/97718086/222878316-a6c5236f-28b0-470b-9b46-6596179f366e.png)

**Comment by gbprod** [comment]
Interesting, I'll take a look soon.

**Comment by gbprod** [comment]
When you say Magit, you talk about https://github.com/TimUntersberger/neogit ?

**Comment by kraanzu** [comment]
No I'm currently using this one: https://github.com/jreybert/vimagit

But hey! the plugin which you shared looks super awesome and does the work of both fugitive + magit for me :)
Thanks a lot for sharing! I'll use this one for now :D

**Comment by gbprod** [comment]
Should be fixed now, can you confirm ?

**Comment by kraanzu** [comment]
Yes It's working now :)
Thanks @gbprod
