### ISSUE TITLE
Support for semantic token modifiers

### ISSUE THREAD

**Issue by Isrothy** [gbprod/nord.nvim#26]
Now that [this](https://github.com/neovim/neovim/pull/22022) has been merged, is it possible for this plugin to add support for semantic token modifiers?

**Comment by gbprod** [comment]
Can you be more specific about what you mean  ?
Do you know any coloscheme that implements sem tokens?

**Comment by Isrothy** [comment]
For example, [OneDarkPro](https://github.com/olimorris/onedarkpro.nvim/commit/515e4dd63c03292711f05d49d8204a067989a156) implemented this. It, for example, made readonly variables italic and add highlights to functions defined in default library.
And [tokyonight](https://github.com/folke/tokyonight.nvim/commit/c967c2cfdbaa20f2938271b5b57bc435f09e13b6) also made default library special.

**Comment by gbprod** [comment]
Interesting, I have to take a look at this.
