### ISSUE TITLE
Suggestion: Change the insert mode indicator background

### ISSUE THREAD

**Issue by sharpenedblade** [gbprod/nord.nvim#32]
When using `lualine.nvim`, the mode indicator turns a bright white(`nord6`). I think this is very high-contrast and is rather jarring, so I think it would be better to tone it down to a darker white(`nord4`).

**Comment by sharpenedblade** [comment]
After looking at [lua/lualine/themes/nord.lua](https://github.com/gbprod/nord.nvim/blob/main/lua/lualine/themes/nord.lua), I noticed that colors I see being used are from nord, but not the right colors.

**Comment by gbprod** [comment]
Yes, it's better, I'll change it
