### ISSUE TITLE
Need help with colors

### ISSUE THREAD

**Issue by crystalball808** [gbprod/nord.nvim#39]
Here in typescript file you can see that both variables and types are the same color
<img width="547" alt="image" src="https://github.com/gbprod/nord.nvim/assets/34882650/03a673c5-92e7-4837-91f9-bc6a88bef9ad">
The desired way (screenshot from VS Code)
<img width="394" alt="image" src="https://github.com/gbprod/nord.nvim/assets/34882650/a53734cf-8e7f-4cab-974c-704d564f3359">
Please help me to fix this

**Comment by gbprod** [comment]
Hi!
I'm currently on vacation, I'll take a look at this when I come back 😉

**Comment by gbprod** [comment]
Hey, I don't have the same colors as you, can you provide your nvim config and plugin setup ?
Can you also tell me if you are using a Lsp server for Typescript ?

**Comment by crystalball808** [comment]
I use lazy.nvim plugin manager
treesitter and lspconfig
<img width="865" alt="image" src="https://github.com/gbprod/nord.nvim/assets/34882650/dc03cc15-ad01-499a-a15f-d322596675d7">
color scheme setup
<img width="393" alt="image" src="https://github.com/gbprod/nord.nvim/assets/34882650/c45736c2-28cd-4867-9658-426da1b242ab">
If you need any other information, please tell

**Comment by gbprod** [comment]
Hi!
I think it comes from your config, using Lazy you should do something like : 


```lua
require("lazy").setup({
  {
    "gbprod/nord.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      require("nord").setup({ })
      vim.cmd("colorscheme nord")
    end,
  },
  install = {
    colorscheme = { "nord" },
  },
});
```

I should add this to the README
