### ISSUE TITLE
TODO: colors

### ISSUE THREAD

**Issue by melta** [gbprod/nord.nvim#40]
Hello,

Thank you for the great plugin!

I recently observed that the "TODO:", "XXX:", and "FIXME:" tags are not being highlighted as they are in the standard Nord theme for Vim. Could you please guide me on how to enable this feature in the custom theme?
Thank you in advance for your assistance.

Best regards.

**Comment by gbprod** [comment]
I personally use https://github.com/folke/todo-comments.nvim to do that.
I think there are other plugins for that bug this one is great

**Comment by melta** [comment]
Thank you!
