### ISSUE TITLE
neogit integration broken

### ISSUE THREAD

**Issue by marcusramberg** [gbprod/nord.nvim#43]
Hey,
I'm having trouble with nord.nvim and neogit. The diffs are unreadable because the background and foreground is the same color. I believe this has to be fixed in the theme, ref this issue on neogit - https://github.com/NeogitOrg/neogit/issues/807

**Comment by gbprod** [comment]
It should be better now, can you confirm @marcusramberg ?
I do not personnaly use Neogit, so if you have any suggestions, feel free to ask or contribute ;)

**Comment by marcusramberg** [comment]
Can confirm it looks good now. Thanks for the fix!
