### ISSUE TITLE
How to use with LazyVim config

### ISSUE THREAD

**Issue by januz** [gbprod/nord.nvim#58]
Hi, thanks for putting this together! I'm trying to use your plugin with the [LazyVim config](https://www.lazyvim.org/) but I'm not sure whether I'm doing things right as the output looks different from what I expect it to based on your screenshots.

I'm configuring the plugin with 

```lua
return {
  { "gbprod/nord.nvim" },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "nord",
    },
  },
}
```

The NeoTree colors look a bit off, especially for the directories:

<img width="321" alt="image" src="https://github.com/gbprod/nord.nvim/assets/1440498/988c63a2-ee69-41c4-9e1e-14e067603c28">

The autocomplete menu looks different 

<img width="1044" alt="image" src="https://github.com/gbprod/nord.nvim/assets/1440498/90692b5e-8a03-4aa4-93f0-1c4b88d3594a">

Telescope looks differently

<img width="787" alt="image" src="https://github.com/gbprod/nord.nvim/assets/1440498/02eb99a5-ec11-40db-acac-f6f0e1cc2b94">

I wonder whether the last two are just based on your settings for the plugins; if so, would you mind telling me how one gets the border around the extended documentation text and how one gets just the symbols on the left hand side like in your screenshot of the autocompletion and the thicker and colored border in telescope?

Thanks so much for your help!

**Comment by gbprod** [comment]
I am currently on vacation, I will take the time to respond to you when I come back 😉

**Comment by januz** [comment]
Thank so much and enjoy your vacation!

**Comment by gbprod** [comment]
Hi!
I've you tried to reproduce this config : https://github.com/gbprod/nord.nvim#-installation ?

**Comment by januz** [comment]
@gbprod I'm struggling to translate this config into the Lazyvim framework. The installation and configuration of plugins within this framework is different from the configuration you display for the `lazyvim` plugin manager: https://www.lazyvim.org/configuration/plugins (also I just switched from using a standard/Vimscript configuration to Lua so a  lot of things don't make sense for me yet...)

**Comment by gbprod** [comment]
I've you tried like this ?

```lua
return {
  {
    "gbprod/nord.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      require("nord").setup({})
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "nord",
    },
  },
}
```

**Comment by januz** [comment]
Thanks for getting back to me. That configuration throws an error: 
<img width="834" alt="image" src="https://github.com/gbprod/nord.nvim/assets/1440498/9ca4e52f-48a0-404f-ab4c-595f29500749">

**Comment by gbprod** [comment]
I'm not using LazyVim but, refering to the [documentation](https://www.lazyvim.org/configuration/plugins), it seems that configuring plugins is different than in lazy. Maybe like that : 
```lua
return {
  {
    "gbprod/nord.nvim",
    opts = {},
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "nord",
    },
  },
}
```

**Comment by januz** [comment]
Hm, that also throws an error. As I wrote above, I *am* able to generally set up LazyVim with your theme with this command

```lua
return {
  { "gbprod/nord.nvim" },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "nord",
    },
  },
}
```

I'm mostly wondering why the result looks different from the screenshots that you present on GitHub, especially with regard to

- NeoTree colors
- autocomplete
- Telescope

I was wondering whether special configuration of the plugin was needed for that (e.g., why do directories display as blue for you but as cyan for me). But I also wonder whether the last two are just based on your settings for the plugins; if so, would you mind telling me how one gets the border around the extended documentation text and how one gets just the symbols on the left hand side like in your screenshot of the autocompletion and the thicker and colored border in telescope?

Would you mind sending me your vim configuration? Thanks so much for your help!

**Comment by gbprod** [comment]
I think you could ask LazyVim maintainers, I'm sure they will help you better than me 😅

**Comment by januz** [comment]
I will, thanks for your help. If you would be willing to share your `nvim` configuration, that would be fantastic as well. Thanks

**Comment by januz** [comment]
@Sped0n Thanks so much, that did the trick! I didn't know how to properly specify the options.
