### ISSUE TITLE
mini.indentscope support

### ISSUE THREAD

**Issue by Flamme13** [gbprod/nord.nvim#65]
How can you improve the display of the https://github.com/echasnovski/mini.indentscope plugin in your theme?

Now it looks like this:

![image](https://github.com/gbprod/nord.nvim/assets/8742198/58475bcf-525d-4f5b-ad46-3bf15a00e066)

With the theme https://github.com/shaunsingh/nord.nvim it looks like this:

![image](https://github.com/gbprod/nord.nvim/assets/8742198/cb9a604a-d22b-4e53-9cc6-1a17b0363a71)

How can I get this or similar result in your theme?

Thank you!

**Comment by gbprod** [comment]
Interesting, I'll try to fix it, thanks
