### ISSUE TITLE
Highlights don't take effect, all text is white

### ISSUE THREAD

**Issue by g-gaston** [gbprod/nord.nvim#69]
All my text appears white and there are no highlights at all (not even for visual mode). I narrowed it down to the `nord.syntax` and `nord.treesitter` highlights: if I disable those, it seems like the rest of the theme loads well.

I'm using lazy and neovim v0.9.5 and not passing any custom configuration to nord, with all plugins supposedly in the last version. Is it possible that I have to update something or use some different configuration?

I understand I'm not giving a lot of info, so apologies. But I really can't find any error that points me in the right direction.

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188
```

**Comment by XuHenghenglumia** [comment]
Same issue,  just default config.

**Comment by gbprod** [comment]
Can you share your config ?
Do you have [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/) installed ?

**Comment by XuHenghenglumia** [comment]
> Can you share your config ? Do you have [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/) installed ?

init.lua:
```
require("plugins")
```
lua/plugins.lua:
```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
        vim.fn.system({
                "git",
                "clone",
                "--filter=blob:none",
                "https://github.com/folke/lazy.nvim.git",
                "--branch=stable", -- latest stable release
                lazypath,
        })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
        {
                "gbprod/nord.nvim",
                lazy = false,
                priority = 1000,
                config = function()
                        require("nord").setup({})
                        vim.cmd.colorscheme("nord")
                end,
        },
        install = {
                colorscheme = {"nord"},
        },
})
```
when I use this config, nvim make a error:
```
Error detected while processing C:\Users\dell\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: .../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/plugin.lua:67: attempt to call method 'find' (a nil value)
stack traceback:
        .../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/plugin.lua:67: in function 'add'
        .../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/plugin.lua:363: in function 'normalize'
        .../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/plugin.lua:359: in function 'normalize'
        .../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/plugin.lua:43: in function 'parse'
        .../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/plugin.lua:541: in function 'load'
        .../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:37: in function 'setup'
        ...AppData\Local\nvim-data\lazy\lazy.nvim/lua/lazy/init.lua:102: in function 'setup'
        C:\Users\dell\AppData\Local\nvim/lua/plugins.lua:13: in main chunk
        [C]: in function 'require'
        C:\Users\dell\AppData\Local\nvim\init.lua:1: in main chunk
Press ENTER or type command to continue
```
So that I must delete the `install` blocks.

**Comment by gbprod** [comment]
Did you run `:Lazy install` ?

**Comment by XuHenghenglumia** [comment]
> Did you run `:Lazy install` ?

Yes. After install, it look like that
<img width="812" alt="image" src="https://github.com/gbprod/nord.nvim/assets/23731236/9a0dccff-99d4-48ff-9be4-90d94d1bcb8b">

**Comment by fhanzer** [comment]
I had the same problem. After enabling termguicolors (`vim.o.termguicolors = true`) it now works for me.

**Comment by XuHenghenglumia** [comment]
> Oh, nice catch, seems I forgot to add this to the readme...
> Does it fix for others ?

It works for me.😄

**Comment by g-gaston** [comment]
Works for me as well, thanks y'all!
For the record, I'm using (lazy):

```lua
  {
    'gbprod/nord.nvim',
    lazy = false,
    priority = 1000,
    init = function()
      vim.o.termguicolors = true
      vim.cmd.colorscheme 'nord'
    end,
  },
```

**Comment by bckelley** [comment]
> Oh, nice catch, seems I forgot to add this to the readme... Does it fix for others ?

seems this still hasn't made it to the readme probably should as it just fixed this for me.

**Comment by gbprod** [comment]
Fixed here : https://github.com/gbprod/nord.nvim/commit/70fc2425b50396e5f1230200b59527d8440a24df
you don't need to set this anymore ;)
