### ISSUE TITLE
[Neogit] Different Highlight for blue fg 

### ISSUE THREAD

**Issue by kraanzu** [gbprod/nord.nvim#74]
Here's a git diff:

![image](https://github.com/user-attachments/assets/a2f4e901-529d-4f86-9ca2-720d648ed689)

If you hover over `red` and `green` lines, the bg just becomes darker:

![image](https://github.com/user-attachments/assets/96c956ba-d7a4-4e94-830f-7a625efbed67)

![image](https://github.com/user-attachments/assets/981b7598-4fac-4880-835e-91d6b4d095c4)

But for the ones in blue color, it changes to white:

![image](https://github.com/user-attachments/assets/b25fb6b7-09d9-41ea-b15a-44251ace4079)

![image](https://github.com/user-attachments/assets/6e9cb97c-97da-411b-b0d5-c7367841b54d)

**Comment by gbprod** [comment]
Hi @kraanzu 
Nice catch ! I've made something, can you tell me if it's also better for you ?

**Comment by kraanzu** [comment]
Hi @gbprod! Yes I'd love to test
I just pulled the latest changes but don't see any diff, is the feature pushed?
Also, it seems the original issue of the thread is also back

**Comment by gbprod** [comment]
Yes, it's pushed : https://github.com/gbprod/nord.nvim/commit/9e8beea8119a403d033e2f27977e1f4cfa023e94
Can you try again ?

**Comment by kraanzu** [comment]
Hmm...The issue still persists. Lemme double check by manually checking if the lines added are present or nord. Or can I verify this from neovim command?
