### ISSUE TITLE
Can I use on_highlights to change global color definitions?

### ISSUE THREAD

**Issue by bearcatsandor** [gbprod/nord.nvim#79]
My lua-fu is weak.

I like the way nord works, but I'm working on a gray variant for myself.  Is there a way to globally change the color variables such that, for instance, aurora.green becomes #87875F?

Something like the following lines in my config:

on_highlights = function(highlights,colors)
   colors.aurora.green = "#87875F"
  end,

Thank you for the great theme!

**Comment by gbprod** [comment]
hmmm, that's interesting, I've been wondering for a while if I should implement an `on_colors` option like in tokyonight, I'll take a quick look at it

**Comment by bearcatsandor** [comment]
That works wonderfully! Thank you so much!
