### ISSUE TITLE
Weird color combo in code snippets when using `markview`

### ISSUE THREAD

**Issue by kraanzu** [gbprod/nord.nvim#80]
So I'm using [markview.nvim](https://github.com/OXY2DEV/markview.nvim) for markdown previews and the color combo for snippet code is weird

Here's a screenshot:

When markview if off:

![image](https://github.com/user-attachments/assets/0d8dfa48-a604-4134-ab64-d00fe6617be1)

When enabled:

![image](https://github.com/user-attachments/assets/fe96d980-0384-4533-a980-f66d97060882)

-----

With `nordtheme/vim` plugin (+ other theme plugins also look good)

![image](https://github.com/user-attachments/assets/0aaec4e2-3e4d-460d-afc5-41899323aecf)

**Comment by kraanzu** [comment]
Ok I found out, it's the transparency that's causing the issue

**Comment by gbprod** [comment]
I've made some changes and fixed this ;)

**Comment by kraanzu** [comment]
Yep. That works great now for me. Thanks!!
